baseURL = 'http://www.gavialtech.com/'
languageCode = 'pt-br'
title = 'Gavial Tech'
theme = "hello-friend-ng"

[params]
    homeSubtitles = "Não sabemos se é Jacaré, Crocodilo ou Gavial"

    enableSharingButtons = true

[[menu.main]]
    identifier = "sobre"
    name       = "sobre"
    url        = "/about"

[[params.social]]
    name = "github"
    url  = "https://github.com/orgs/GavialInc"

[params.footer]
    trademark = true
    rss = true

[params.logo]
    logoMark = " "
    logoText = "# ./Gavial"
